# Generated by Django 2.2.5 on 2019-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('start_time', models.DateTimeField(verbose_name='実況開始時刻')),
                ('episode', models.IntegerField(null=True, verbose_name='話数')),
                ('comment', models.TextField(verbose_name='コメント')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
