# Generated by Django 2.2.5 on 2019-09-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190908_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(verbose_name='開始時刻'),
        ),
    ]
